# Generated by Django 5.0.2 on 2024-02-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_breakdown_exam_question_exammodule_exam_modules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='question',
            new_name='questions',
        ),
    ]
