# Generated by Django 5.0.2 on 2024-02-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_rename_question_exam_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='answaer',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='correct',
            field=models.CharField(default='-', max_length=5),
        ),
    ]
