# Generated by Django 5.0.2 on 2024-02-27 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_breakdown_answaer_alter_breakdown_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakdown',
            old_name='answaer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='exammodule',
            old_name='activate',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='updated',
        ),
        migrations.AddField(
            model_name='exam',
            name='update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de actualizacion'),
            preserve_default=False,
        ),
    ]
